### ISSUE TITLE
Typo "that their goals with v included"

### ISSUE THREAD

**Issue by lwolberg** [w3c/captcha-accessibility#17]
Change
that their goals with v included
To 
that their goals with v3 included

**Comment by lwolberg** [comment]
One more: this "V" is unclear

as a fallback mechanism and has dropped it from v reCAPTCHA

**Comment by jasonjgw** [comment]
Having checked Google's documentation, it appears that the reference should be to v3 in both instances. I have created a pull request accordingly.
